export const BUTTON_QUERY = {
    'pagination_next': 'pagination_next',
    'pagination_back': 'pagination_back',
    'create_new': 'create_new',
    'pagination_close': 'pagination_close',
    'account_accumulative_type': 'account_accumulative_type',
    'account_purpose_type': 'account_purpose_type',
    'account_usd_currency': 'account_usd_currency',
    'account_rub_currency': 'account_rub_currency',
    'save': 'save',
    'edit': 'edit',
    'delete': 'delete',
    'skip': 'skip',
    'show_transaction': 'show_transaction',
    'add_transaction': 'add_transaction',
    'confirm': 'confirm',
    'sort_amount_desc': 'sort_amount_desc',
    'sort_amount_asc': 'sort_amount_asc',
    'sort_target_desc': 'sort_target_desc',
    'sort_target_asc': 'sort_target_asc',
    'sort_date_desc': 'sort_date_desc',
    'sort_date_asc': 'sort_date_asc'
};